import { getBusinesses, newYorkBizArr, manufacturingBizArr, agentArr } from "./businessData.js";
import { agentHTML, businessHTML } from "./business.js";

// ==================================================== active businesses ====================================================
export const businessList = () => {
    // points to where to inject into html
    const contentElement = document.querySelector(".businesses")
    // pulls data from another file and stores it in a variable
    const biz = getBusinesses()

    // empty string to build the html into
    let bizHTMLrep = ""

    // itterates through the array of objects with the businessHTML function
    biz.forEach(element => {
        bizHTMLrep += businessHTML(element)
    })

    // sets the DOM equal to the variable holding the HTML generated by businessHTML
    contentElement.innerHTML += `${bizHTMLrep}`
}

// ==================================================== new york businesses ====================================================
export const newYorkBusinessList = () => {
    // points to where to inject into html
    const contentElement = document.querySelector(".businessList--newYork")
    
    // empty string to build the html into
    let bizHTMLrep = ""

    // itterates through the array of objects with the businessHTML function
    newYorkBizArr.forEach(element => {
        bizHTMLrep += businessHTML(element)
    })

    // sets the DOM equal to the variable holding the HTML generated by businessHTML
    contentElement.innerHTML += `${bizHTMLrep}`
}

// ==================================================== manufacturing businesses ====================================================
export const manufacturingBusinessList = () => {
    // points to where to inject into html
    const contentElement = document.querySelector(".businessList--manufacturing")

    // empty string to build the html into
    let bizHTMLrep = ""

    // itterates through the array of objects with the businessHTML function
    manufacturingBizArr.forEach(element => {
        bizHTMLrep += businessHTML(element)
    })

    // sets the DOM equal to the variable holding the HTML generated by businessHTML
    contentElement.innerHTML += `${bizHTMLrep}`
}

// ==================================================== purchasing agents ====================================================
export const purchasingAgentList = () => {
    // points to where to inject into html
    const contentElement = document.querySelector(".agents")

    // empty string to build the html into
    let bizHTMLrep = ""

    // itterates through the array of objects with the businessHTML function
    agentArr.forEach(element => {
        bizHTMLrep += agentHTML(element)
    })

    // sets the DOM equal to the variable holding the HTML generated by businessHTML
    contentElement.innerHTML += `${bizHTMLrep}`
}

// ==================================================== search bar w/ business names ====================================================
// Place an article element in your HTML with the class below
// const companySearchResultArticle = document.querySelector(".foundCompanies")

// document
//     .querySelector("#companySearch")
//     .addEventListener("keypress", keyPressEvent => {
//         if (keyPressEvent.charCode === 13) {
//             /*
//                 When user presses enter, find the matching business.
//                 You can use the `.includes()` method strings to
//                 see if a smaller string is part of a larger string.

//                 Example:
//                     business.companyName.includes(keyPressEvent.target.value)
//             */

//             const foundBusiness = getBusinesses().find(biz => biz.companyName.includes(keyPressEvent.target.value)) // implement .find() method here

//             companySearchResultArticle.innerHTML = `
//                 <h2>
//                     ${foundBusiness.companyName}
//                 </h2>
//                 <section>
//                     ${foundBusiness.addressFullStreet}
//                 </section>
//                 <section>
//                     ${foundBusiness.addressCity},
//                     ${foundBusiness.addressStateCode}
//                     ${foundBusiness.addressZipCode}
//                 </section>
//             `;
//         }
//     });

// ==================================================== search bar w/ purchasing agent names ====================================================
const companySearchResultArticle = document.querySelector(".foundCompanies")

document
    .querySelector("#companySearch")
    .addEventListener("keypress", keyPressEvent => {
        if (keyPressEvent.charCode === 13) {

            const foundBusiness = agentArr.find(biz => biz.fullName.includes(keyPressEvent.target.value))

            companySearchResultArticle.innerHTML = `
                <h2>
                    ${foundBusiness.fullName}
                </h2>
                <section>
                    ${foundBusiness.company}
                </section>
                <section>
                    ${foundBusiness.phoneNumber}
                </section>
            `;
        }
    });