import { getBusinesses, newYorkBizArr, manufacturingBizArr } from "./businessData.js";
import { businessHTML } from "./business.js";

export const businessList = () => {
    // points to where to inject into html
    const contentElement = document.querySelector(".businesses")
    // pulls data from another file and stores it in a variable
    const biz = getBusinesses()

    // empty string to build the html into
    let bizHTMLrep = ""

    // itterates through the array of objects with the businessHTML function
    biz.forEach(element => {
        bizHTMLrep += businessHTML(element)
    })

    // sets the DOM equal to the variable holding the HTML generated by businessHTML
    contentElement.innerHTML += `${bizHTMLrep}`
}

export const newYorkBusinessList = () => {
    // points to where to inject into html
    const contentElement = document.querySelector(".businessList--newYork")
    
    // empty string to build the html into
    let bizHTMLrep = ""

    // itterates through the array of objects with the businessHTML function
    newYorkBizArr.forEach(element => {
        bizHTMLrep += businessHTML(element)
    })

    // sets the DOM equal to the variable holding the HTML generated by businessHTML
    contentElement.innerHTML += `${bizHTMLrep}`
}

export const manufacturingBusinessList = () => {
    // points to where to inject into html
    const contentElement = document.querySelector(".businessList--manufacturing")

    // empty string to build the html into
    let bizHTMLrep = ""

    // itterates through the array of objects with the businessHTML function
    manufacturingBizArr.forEach(element => {
        bizHTMLrep += businessHTML(element)
    })

    // sets the DOM equal to the variable holding the HTML generated by businessHTML
    contentElement.innerHTML += `${bizHTMLrep}`
}